#!/bin/bash

# Create XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

# Create symlinks for configs in repo
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.vimrc" "$HOME"/.vimrc
ln -sf "$PWD/.zshrc" "$HOME"/.zshrc

# Install packages within container
packages=(
  vim
  kubectl
  fluxcd/tap/flux
  direnv
  k9s
  pure
  sops
  nvim
  lazygit
)

# Loop through array above and install each package
for package in "${packages[@]}"; do
  echo "Installing $package..."
  /home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

echo "All packages successfully installed."

echo "Setup complete."
